import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import BodyLayout from "@/components/BodyLayout";
import { AuthProvider } from "@/contextapi/provider";
import ReactQueryProvider from "@/contextapi/ReactQueryClientProvider";
import AlertModal from "@/components/AlertModal";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-white text-black dark:bg-[#333333] dark:text-[#F1F5F9]  lg:max-w-300 lg:mx-auto`}
      >
        <AlertModal />
        <ReactQueryProvider>
          <AuthProvider>
            <BodyLayout>
              {children}
              <AlertModal />
            </BodyLayout>
          </AuthProvider>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
